GET http://localhost:3000/api/offers
Accept: application/json

###
#GET http://localhost:3000/api/offers2
#Accept: application/json

###
GET http://localhost:3000/api/offers/2
Accept: application/json

###
GET http://localhost:3000/api/categories
Accept: application/json

###
POST http://localhost:3000/api/offers
Content-Type: application/json

{
  "categories": [1,2],
  "description": "new description",
  "picture": "1.jpg",
  "title": "title",
  "type": "buy",
  "sum": 12345,
  "userId": 1
}

###
PUT http://localhost:3000/api/offers/1
Content-Type: application/json

{
  "categories": [1,2,3],
  "description": "update description",
  "picture": "1.jpg",
  "title": "update title",
  "type": "sell",
  "sum": 654321,
  "userId": 2
}

###
PUT http://localhost:3000/api/offers/1
Content-Type: application/json

{
  "category": "update category",
  "description": "update description",
  "picture": "1.jpg",
  "sum": 321
}

###
DELETE http://localhost:3000/api/offers/1

###
GET http://localhost:3000/api/offers/2/comments
Accept: application/json

###
DELETE http://localhost:3000/api/offers/2/comments/2
Accept: application/json

###
POST http://localhost:3000/api/offers/2/comments
Content-Type: application/json

{
  "text": "new comment text",
  "userId": 1
}

###
GET http://localhost:3000/api/search?query=Продам
Accept: application/json
