GET http://localhost:3000/api/offers
Accept: application/json

###
GET http://localhost:3000/api/offers/21gPZr
Accept: application/json

###
GET http://localhost:3000/api/categories
Accept: application/json

###
POST http://localhost:3000/api/offers
Content-Type: application/json

{
  "category": "new category",
  "description": "new description",
  "picture": "1.jpg",
  "title": "title",
  "type": "default type",
  "sum": 123
}

###
POST http://localhost:3000/api/offers
Content-Type: application/json

{
  "category": "new category",
  "description": "new description",
  "picture": "1.jpg",
  "title": "title",
  "type": "default type",
  "sum": 1234
}

###
PUT http://localhost:3000/api/offers/LvViKa
Content-Type: application/json

{
  "category": "update category",
  "description": "update description",
  "picture": "1.jpg",
  "title": "update title",
  "type": "update type",
  "sum": 321
}

###
PUT http://localhost:3000/api/offers/21gPZr
Content-Type: application/json

{
  "category": "update category",
  "description": "update description",
  "picture": "1.jpg",
  "sum": 321
}

###
DELETE http://localhost:3000/api/offers/aZjT9E

###
GET http://localhost:3000/api/offers/HiSudj/comments
Accept: application/json

###
DELETE http://localhost:3000/api/offers/HiSudj/comments/21gPZr
Accept: application/json

###
POST http://localhost:3000/api/offers/21gPZr/comments
Content-Type: application/json

{
  "text": "new comment text"
}

###
GET http://localhost:3000/api/search?query=санки
Accept: application/json
