###
GET http://localhost:8080/

###
GET http://localhost:8080/register

###
GET http://localhost:8080/login

###
GET http://localhost:8080/search

###
GET http://localhost:8080/my

###
GET http://localhost:8080/my/comments

###
GET http://localhost:8080/offers/category/2

###
GET http://localhost:8080/offers/add

###
GET http://localhost:8080/offers/edit/3

###
GET http://localhost:8080/offers/5

###
GET http://localhost:8080/not-found
